CREATE TABLE delivery_observatory_runs (
  organization_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  run_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  selection_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  decision_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  decision_canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  configuration_canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  workflow_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  workflow_canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schema_version VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  runner_version VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mode VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  data_state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  outcome VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  remote_write_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  run_json JSON NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (organization_id, project_id, run_id),
  UNIQUE KEY uq_delivery_observatory_input (organization_id, project_id, input_hash),
  KEY idx_delivery_observatory_selection (organization_id, project_id, selection_id, created_at),
  CONSTRAINT fk_delivery_observatory_selection FOREIGN KEY (organization_id, project_id, selection_id)
    REFERENCES delivery_decision_selections (organization_id, project_id, selection_id),
  CONSTRAINT chk_delivery_observatory_source CHECK (source IN ('mock','replay')),
  CONSTRAINT chk_delivery_observatory_mode CHECK (mode IN ('observe_existing','prepare_new_local_form')),
  CONSTRAINT chk_delivery_observatory_data_state CHECK (data_state IN ('ready','insufficient_data','stale_data','blocked_by_asset','platform_pending')),
  CONSTRAINT chk_delivery_observatory_action_boundary CHECK (remote_write_enabled = FALSE),
  CONSTRAINT chk_delivery_observatory_json_write_flag CHECK (JSON_UNQUOTE(JSON_EXTRACT(run_json, '$.remote_write_enabled')) = 'false'),
  CONSTRAINT chk_delivery_observatory_no_executable_remote_write CHECK (JSON_SEARCH(run_json, 'one', 'remote_write', NULL, '$.steps[*].executed_action') IS NULL),
  CONSTRAINT chk_delivery_observatory_status CHECK (status IN ('completed','blocked','runner_failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE delivery_observatory_feedback (
  organization_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  project_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  feedback_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  run_id VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  run_canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  schema_version VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  disposition VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  final_configuration_canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  canonical_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  feedback_json JSON NOT NULL,
  idempotency_key VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (organization_id, project_id, feedback_id),
  UNIQUE KEY uq_delivery_observatory_feedback_idempotency (organization_id, project_id, idempotency_key),
  KEY idx_delivery_observatory_feedback_run (organization_id, project_id, run_id, created_at),
  CONSTRAINT fk_delivery_observatory_feedback_run FOREIGN KEY (organization_id, project_id, run_id)
    REFERENCES delivery_observatory_runs (organization_id, project_id, run_id),
  CONSTRAINT chk_delivery_observatory_feedback_disposition CHECK (disposition IN ('accepted','modified','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
